language: java
jdk:
  - openjdk17

# Usar el "wrapper" de Maven que subiste para asegurar la versión correcta
script:
  - ./mvnw clean test

# Guardar en caché las dependencias para que las pruebas sean rápidas
cache:
  directories:
    - $HOME/.m2
